package com.gaja.app.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2019-11-09T19:51:38.354+03:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://service.app.gaja.com/", name = "CalculatorService")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculatorService {

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://service.app.gaja.com/", className = "com.gaja.app.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.app.gaja.com/", className = "com.gaja.app.service.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.gaja.app.service.Response add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.gaja.app.service.Request arg0
    );
}
